{% set name = "slurm-pipeline" %}
{% set version = "4.0.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slurm-pipeline-{{ version }}.tar.gz
  sha256: 05a8650944f4cb738c91a782c6247a37f6b867abbc973e93bb083704c31e6479

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pytest >=6.2.2
    - python >=3.6

test:
  imports:
    - slurm_pipeline
  source_files:
    - test
  commands:
    - pip check
    - pytest test
  requires:
    - pip
    - pytest

about:
  home: https://github.com/acorg/slurm-pipeline
  summary: A Python class and utility script for scheduling SLURM jobs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - terrycojones
