{% set name = "slurm-pipeline" %}
{% set version = "4.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slurm-pipeline-{{ version }}.tar.gz
  sha256: f3cbe63e3dedfe04e3d2638921ba66bc1966f0e290cb3fa71830475446fe71ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pytest >=6.2.2
    - python >=3.6

test:
  imports:
    - slurm_pipeline
  source_files:
    - test
  commands:
    - pip check
    - pytest test
  requires:
    - pip
    - pytest

about:
  home: https://github.com/acorg/slurm-pipeline
  summary: A Python class and utility script for scheduling SLURM jobs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - terrycojones
