{% set name = "slurm-pipeline" %}
{% set version = "4.0.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slurm-pipeline-{{ version }}.tar.gz
  sha256: 9bf9434b366af42eec5e7a476b711641974a8d9c5c188134b7ea1caf4a139e69

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - pandas
    - pip
    - plotly
    - pytest >=6.2.2
    - python >=3.6

test:
  imports:
    - slurm_pipeline
  source_files:
    - test
  commands:
    - pip check
    - pytest test
  requires:
    - pandas
    - pip
    - plotly
    - pytest

about:
  home: https://github.com/acorg/slurm-pipeline
  summary: A Python class and utility script for scheduling SLURM jobs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - terrycojones
